create-package: improve error detection

diff --git a/create-package b/create-package
--- a/create-package
+++ b/create-package
@@ -3,6 +3,7 @@
 CYAN="\e[0;36m"
 RED="\e[0;91m"
 NORMAL="\e[0m"
+BOLD="\e[1m"
 
 function info() {
 	echo -e "${CYAN}${1}${NORMAL}"
@@ -10,6 +11,12 @@ function info() {
 
 function warning() {
 	echo -e "${RED}${1}${NORMAL}"
+}
+
+function abort() {
+	printf "  ${RED}%s[%s]:${NORMAL}" "${BASH_SOURCE[1]}" ${BASH_LINENO[0]}
+	echo -e " ${RED}${REVERSE}$@${NORMAL} ${RED}Aborting...${NORMAL}"
+	exit 2
 }
 
 which_path() {
@@ -72,16 +79,14 @@ if [ -z "${EXE}" ]; then
 
 
 	if [ -z "$package" ]; then
-		warning "No package matching that name found, sorry."
-		exit 1
-
+		abort "No package matching '${BOLD}$package${NORMAL}' was found, sorry."
 	elif [[ "$package" =~ $'\n' ]]; then
 		info "More than one package matching that name was found, maybe you want one of them?"
 		echo "$package" | sed 's/^/  - /'
 		info "If you want to install one of them, run ./chroot-gentoo -c 'emerge -v <package name>'"
 		exit 1
 	else
-		info "Found matching package ${package}."
+		info "Found matching package ${BOLD}${package}${NORMAL}."
 		count=5
 		warning "Installing it in ${count} seconds, press Ctrl+C to abort!"
 		while ((count-- > 0)); do
@@ -89,7 +94,8 @@ if [ -z "${EXE}" ]; then
 			sleep 1
 		done
 		echo -e "\nRunning ./chroot-gentoo -c 'emerge ${package}'"
-		./chroot-gentoo -c "emerge ${package}"
+		./chroot-gentoo -c "emerge ${package}" \
+			|| abort "failed to emerge ${package}"
 	fi
 
 
@@ -99,8 +105,7 @@ if [ -z "${EXE}" ]; then
 	EXE=$(which_path "${NAME}")
 
 	if [ -z "${EXE}" ]; then
-		warning "Still not finding ${NAME}, don't know what more to do, sorry..."
-		exit
+		abort "Still not finding ${NAME}, don't know what more to do, sorry..."
 	fi
 fi
 
@@ -118,9 +123,10 @@ fi
 		--dest "$DEST" \
 		"$@"
 )
-
-if [ $? = 0 ]; then
+ret=$?
+if [ $ret = 0 ]; then
 	echo -e "$DEST created, enjoy!"
 else
 	echo -e "Something wrong probably happened with ${EXE}, sorry..."
 fi
+exit $ret
